
[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"
[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[window]
dynamic_title = true

[window.padding]
x = 5
y = 5

[general]
import = ["/home/michmich455/.config/alacritty/colors.toml"]
