import = ["/home/michmich455/.config/alacritty/colors.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.normal]
family = "JetBrainsMono NFM"
style = "Book"

[window]
dynamic_title = true

[window.padding]
x = 5
y = 5
