# Font
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
font_size        11.0

# Window
window_padding_width 5

# Catppuccin Mocha
background            #24273A
foreground            #CAD3F5
cursor                #F4DBD6
cursor_text_color     #24273A
selection_background  #F4DBD6
selection_foreground  #24273A

# Normal colors
color0  #494D64
color1  #ED8796
color2  #A6DA95
color3  #EED49F
color4  #8AADF4
color5  #F5BDE6
color6  #8BD5CA
color7  #B8C0E0

# Bright colors
color8   #5B6078
color9   #ED8796
color10  #A6DA95
color11  #EED49F
color12  #8AADF4
color13  #F5BDE6
color14  #8BD5CA
color15  #A5ADCB

# Allow remote control (for dynamic title etc.)
allow_remote_control yes

# Disable close confirmation prompt
confirm_os_window_close 0
